help:
	@echo 'Build {{.ModuleName}}'

fmt:
	echo "go formatting..."
	gofmt -w .

protos:
	echo "Compiling proto files..."
	mkdir -p models && protoc --go_out=./models/ ./proto/state.proto

proto-clean:
	rm -rf models/

build:
	mkdir -p bin/ && go build  -o bin/{{.ModuleName}} {{.Org}}/{{.ModuleName}}/cmd

all: fmt protos build

test:
	echo "Running tests"
	go test {{.Org}}/{{.ModuleName}}/...

test: fmt protos test

clean: proto-clean
	rm -rf bin/